### ISSUE TITLE
Running test.py get an error

### ISSUE THREAD

**Issue by tigermask1978** [Stick-To/RefineDet-tensorflow#11]
My env:
    OS: win10 64bit
   tensorflow: 1.15
   python: 3.7
When I run test.py I got the follow error:
2019-12-25 19:13:44.116978: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: DatasetV1.output_types (from tensorflow.python.data.ops.dataset_ops)
is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:347: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:348: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:350: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:44: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:70: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:73: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:661: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\layers\pooling.py:311: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:632: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:610: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and
will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:647: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2DTranspose` instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:516: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:516: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:534: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:167: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:169: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:172: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:172: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:563: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:568: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:569: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:557: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2019-12-25 19:14:09.015147: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-12-25 19:14:09.165160: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 750 Ti major: 5 minor: 0 memoryClockRate(GHz): 1.1105
pciBusID: 0000:01:00.0
2019-12-25 19:14:09.175969: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-12-25 19:14:09.184199: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-12-25 19:14:09.192621: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll

(base) C:\MyScripts\tf\RefineDet-tensorflow-bolt>python test.py
2019-12-25 19:39:22.475671: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\autograph\converters\directives.py:119: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: The name tf.data.Iterator is deprecated. Please use tf.compat.v1.data.Iterator instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: DatasetV1.output_types (from tensorflow.python.data.ops.dataset_ops)
is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\utils\tfrecord_voc_utils.py:119: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:347: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:348: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:350: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:44: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:70: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:73: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:661: max_pooling2d (from tensorflow.python.layers.pooling) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.MaxPooling2D instead.
WARNING:tensorflow:From C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\layers\pooling.py:311: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:632: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:610: batch_normalization (from tensorflow.python.layers.normalization) is deprecated and
will be removed in a future version.
Instructions for updating:
Use keras.layers.BatchNormalization instead.  In particular, `tf.control_dependencies(tf.GraphKeys.UPDATE_OPS)` should not be used (consult the `tf.keras.layers.batch_normalization` documentation).
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:647: conv2d_transpose (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2DTranspose` instead.
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:516: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:516: The name tf.losses.Reduction is deprecated. Please use tf.compat.v1.losses.Reduction instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:534: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:167: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:169: The name tf.trainable_variables is deprecated. Please use tf.compat.v1.trainable_variables instead.

C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:172: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:172: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:563: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:568: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:569: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:557: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.

2019-12-25 19:39:47.632830: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-12-25 19:39:47.816309: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 750 Ti major: 5 minor: 0 memoryClockRate(GHz): 1.1105
pciBusID: 0000:01:00.0
2019-12-25 19:39:47.823196: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-12-25 19:39:47.831045: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-12-25 19:39:47.844430: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2019-12-25 19:39:47.852309: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2019-12-25 19:39:47.864878: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2019-12-25 19:39:47.876767: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2019-12-25 19:39:47.891939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-12-25 19:39:47.899592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-25 19:39:49.271848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-25 19:39:49.277090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-12-25 19:39:49.280018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-12-25 19:39:49.284579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1374 MB memory) -> physical GPU (device: 0, name: GeForce GTX 750 Ti, pci bus id: 0000:01:00.0, compute capability: 5.0)
WARNING:tensorflow:From C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py:558: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Traceback (most recent call last):
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[{{node save/RestoreV2}}]]
  (1) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[{{node save/RestoreV2}}]]
         [[save/RestoreV2/_83]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[node save/RestoreV2 (defined at C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
  (1) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[node save/RestoreV2 (defined at C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
         [[save/RestoreV2/_83]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "test.py", line 65, in <module>
    refinedet = net.RefineDet320(config, trainset_provider)
  File "C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py", line 49, in __init__
    self._create_saver()
  File "C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py", line 563, in _create_saver
    self.saver = tf.train.Saver()
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 66, in <module>
    refinedet.load_weight('C:\\MyScripts\\tf\\RefineDet-tensorflow-bolt\\vgg_16_2016_08_28\\vgg_16.ckpt')
  File "C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py", line 603, in load_weight
    self.saver.restore(self.sess, path)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

2 root error(s) found.
  (0) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[node save/RestoreV2 (defined at C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
  (1) Not found: Tensor name "ARM/arm1/batch_normalization/beta" not found in checkpoint files C:\MyScripts\tf\RefineDet-tensorflow-bolt\vgg_16_2016_08_28\vgg_16.ckpt
         [[node save/RestoreV2 (defined at C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
         [[save/RestoreV2/_83]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "test.py", line 65, in <module>
    refinedet = net.RefineDet320(config, trainset_provider)
  File "C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py", line 49, in __init__
    self._create_saver()
  File "C:\MyScripts\tf\RefineDet-tensorflow-bolt\RefineDet.py", line 563, in _create_saver
    self.saver = tf.train.Saver()
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\MySoftWare\Anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

It seems to fail to load the vgg_16.ckpt or I missed something?

**Comment by Stick-To** [comment]
vgg16.ckpt is the pretrained backone, not  the whole refinedet
